[package]
name = "candle"
version = "0.6.0"
authors = ["Gabe Berke-Williams <gabebw@gabebw.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8"
isatty = "0.1"
regex = "1"
scraper = "*"
